export const ALL_PROPERTY_REQUEST = "ALL_PROPERTY_REQUEST";
export const ALL_PROPERTY_SUCCESS = "ALL_PROPERTY_SUCCESS";
export const ALL_PROPERTY_FAIL = "ALL_PROPERTY_FAIL";

export const ADMIN_PROPERTY_REQUEST = "ADMIN_PROPERTY_REQUEST";
export const ADMIN_PROPERTY_SUCCESS = "ADMIN_PROPERTY_SUCCESS";
export const ADMIN_PROPERTY_FAIL = "ADMIN_PROPERTY_FAIL";

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST";
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS";
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL";

export const NEW_PROPERTY_REQUEST = "NEW_PROPERTY_REQUEST";
export const NEW_PROPERTY_SUCCESS = "NEW_PROPERTY_SUCCESS";
export const NEW_PROPERTY_RESET = "NEW_PROPERTY_RESET";
export const NEW_PROPERTY_FAIL = "NEW_PROPERTY_FAIL";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_RESET = "UPDATE_PROPERTY_RESET";
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY_REQUEST";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_RESET = "DELETE_PROPERTY_RESET";
export const DELETE_PROPERTY_FAIL = "DELETE_PROPERTY_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";